[package]
authors = ["Bjorn Tipling <bjorn@ambientchill.com>"]
name = "sphela"
version = "0.1.0"

[dependencies]
clap = "2.32.0"
hyper = "0.12.13"
pretty_env_logger = "0.2.5"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
toml = "0.4.8"
futures = "0.1.25"
tokio = "0.1.11"
