[package]
authors = ["Bjorn Tipling <bjorn@ambientchill.com>"]
edition = "2018"
name = "sphela"
version = "0.1.0"

[dependencies]
clap = "2.32.0"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
toml = "0.4.8"
